version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -c 'mix ecto.create && mix ecto.migrate && mix phx.server'
    environment:
      MIX_ENV: dev
      DATABASE_URL: postgres://postgres:postgres@channelspike_db:5432/discuss_dev
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/deps/

  channelspike_db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin_channelspike_db:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./docker/development/pgadmin.json:/pgadmin4/servers.json
      - ./docker/development/pgpass:/pgpass